### ISSUE TITLE
Import error when running app.py

### ISSUE THREAD

**Issue by Clara-liu** [aadityaubhat/auto-analyst#4]
Thanks for a great looking tool. I am having some trouble trying to use it at the moment.

As per title, after installing the dependencies and running `streamlit run auto_analyst/app.py`, the below error occurs:
```
2023-06-28 17:18:06.387 Uncaught app exception
Traceback (most recent call last):
  File "/Users/user/virtual_envs/auto_analyst/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
  File "/Users/user/opt/auto-analyst/auto_analyst/app.py", line 2, in <module>
    from .auto_analyst import AutoAnalyst
ImportError: attempted relative import with no known parent package
```

**Comment by aadityaubhat** [comment]
Hi Clara, thanks for checking this project out. The new app is a Flask app, to run the app you can 

* Clone the repo
* Create Python virtual environment
* Install requirements.txt
* From auto-analyst directory run `python -m auto_analyst.app`
* Open the app in the browser at `http://localhost:5000/` 

Let me know if that doesn't work. I'll update the readme and screenshots to reflect the newer app soon.

**Comment by Clara-liu** [comment]
That worked many thanks. I'll mark this as resolved.
